# -*- coding: utf-8 -*-
"""Yolo_TEX.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fW_lEgDnmoEjc62gaWzqCf_QOdR6OxJz
"""

!nvidia-smi

!ls -lh /content

"""2.1 Upload images
First, we need to upload the dataset to Colab. Here are a few options for moving the data.zip folder into this Colab instance.

Option 1. Upload through Google Colab

Upload the data.zip file to the Google Colab instance by clicking the "Files" icon on the left hand side of the browser, and then the "Upload to session storage" icon. Select the zip folder to upload it.



"""

# Unzip images to a custom data folder
!unzip -q /content/completo_yolov8.zip -d /content/custom_data



!pip install ultralytics

"""Now that the data is organized and the config file is created, we're ready to start training! First, there are a few important parameters to decide on. Visit my article on Training YOLO Models Locally to learn more about these parameters and how to choose them.

Model architecture & size (model):

There are several YOLO11 models sizes available to train, including yolo11n.pt, yolo11s.pt, yolo11m.pt, yolo11l.pt, and yolo11xl.pt. Larger models run slower but have higher accuracy, while smaller models run faster but have lower accuracy. I made a brief YouTube video that compares performance of different YOLO models on a Raspberry Pi 5 and a laptop with a RTX 4050 GPU, check it out here to get a sense of their speed accuracy. If you aren't sure which model size to use, yolo11s.pt is a good starting point.

You can also train YOLOv8 or YOLOv5 models by substituting yolo11 for yolov8 or yolov5.

Number of epochs (epochs)

In machine learning, one “epoch” is one single pass through the full training dataset. Setting the number of epochs dictates how long the model will train for. The best amount of epochs to use depends on the size of the dataset and the model architecture. If your dataset has less than 200 images, a good starting point is 60 epochs. If your dataset has more than 200 images, a good starting point is 40 epochs.

Resolution (imgsz)

Resolution has a large impact on the speed and accuracy of the model: a lower resolution model will have higher speed but less accuracy. YOLO models are typically trained and inferenced at a 640x640 resolution. However, if you want your model to run faster or know you will be working with low-resolution images, try using a lower resolution like 480x480.

Run the following code block to begin training. If you want to use a different model, number of epochs, or resolution, change model, epochs, or imgsz.
"""

from ultralytics import YOLO

# CHANGE TO NANO SMALL
# ITS FASTER, THE IDEAL FOR BALANCE BETWEEN FPS AND PRECISION.
model = YOLO('yolov8s.pt')

model.train(
    data='/content/custom_data/data.yaml',

    #
    epochs=100,
    patience=10,

    #
    imgsz=512,

    batch=64,

    #
    optimizer='auto',
    lr0=0.01,

    #
    plots=True,
    save=True
)

"""6. **Test Model**
The model has been trained; now it's time to test it! The commands below run the model on the images in the validation folder and then display the results for the first 10 images. This is a good way to confirm your model is working as expected. Click Play on the blocks below to see how your model performs.
"""

!yolo detect predict model=runs/detect/train/weights/best.pt source=custom_data/valid/images save=True

import glob
from IPython.display import Image, display
for image_path in glob.glob(f'/content/runs/detect/predict/*.jpg')[:10]:
  display(Image(filename=image_path, height=400))
  print('\n')

"""7.1 Download YOLO Model
First, zip and download the trained model by running the code blocks below.

The code creates a folder named my_model, moves the model weights into it, and renames them from best.pt to my_model.pt. It also adds the training results in case you want to reference them later. It then zips the folder as my_model.zip.
"""

# Commented out IPython magic to ensure Python compatibility.
# Create "my_model" folder to store model weights and train results
!mkdir /content/my_modeltexx3
!cp /content/runs/detect/train2/weights/best.pt /content/my_modeltexx3/my_modeltexx3.pt
!cp -r /content/runs/detect/train2 /content/my_modeltexx3/train

# ZIP ALL
# %cd /content/my_modeltexx3
!zip -r /content/my_modeltexx3.zip my_modeltexx3.pt train
# %cd /content